# Generated by Django 5.2.8 on 2025-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GastoVariavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data_gasto", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("alimentacao", "Alimentação"),
                            ("transporte", "Transporte"),
                            ("lazer", "Lazer"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
