# Generated by Django 5.2.8 on 2025-11-30 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('criado', models.DateField()),
                ('dia_pagamento', models.IntegerField(help_text='Dia do mês em que normalmente se paga este gasto (1 a 31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('bancoPagador', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroGastoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True)),
                ('dataPagamento', models.DateField()),
                ('valorPago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_fixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='core.gastofixo')),
            ],
        ),
    ]
