# Generated by Django 5.2.8 on 2025-12-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_gastofixo_registrogastofixo"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastofixo",
            name="formaPagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Débito Automatico", "Débito Automatico"),
                    ("Pix", "Pix"),
                    ("Cartão de Crédito", "Cartão de Crédito"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
