# Generated by Django 5.2.8 on 2025-12-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_gastofixo_formapagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gastofixo",
            name="criado",
            field=models.DateField(auto_created=True),
        ),
    ]
