# Generated by Django 5.2.8 on 2025-12-04 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_gastofixo_criado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceitaFixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=80)),
                (
                    "dataRecebimento",
                    models.IntegerField(
                        help_text="Dia do mês em que normalmente se paga este gasto (1 a 31).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "receitaEsperada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("bancoRecebedor", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="gastofixo",
            name="formaPagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Débito Automatico", "Débito Automatico"),
                    ("Pix", "Pix"),
                    ("Débito em Conta", "Débito em Conta"),
                    ("Cartão de Crédito", "Cartão de Crédito"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
