# Generated by Django 5.2.8 on 2025-12-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_receitafixa_alter_gastofixo_formapagamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroReceitaFixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataRecebimento", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "receita_fixa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="core.receitafixa",
                    ),
                ),
            ],
        ),
    ]
